baseURL = "/"
languageCode = "en-us"
themesDir = "../themes"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"

[module]
# The following mounts are required for the theme to be able to load bootstrap
# Remember also to copy the theme's `package.json` to your site, and run `npm install`
[[module.mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/scss/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/vendor/bootstrap.bundle.min.js"

[[module.mounts]]
source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
target = "assets/css/bootstrap-print.css"

# navigation
[menu]

[[menu.header]]
URL = "#experience"
name = "experiences"
weight = 2

[[menu.header]]
URL = "#client-and-work"
name = "Projects"
weight = 3

[[menu.header]]
URL = "#contact"
name = "Contact"
weight = 4

[params]

sections = ["showcase", "links", "education", "experience", "client-and-work", "contact"]

homepageExperienceCount = 4

[params.logo]
text1 = "Ming "
text2 = "Soon Ang"

[params.footer]
copyright = "© Ming Soon Ang. Free Hugo theme by Adrián Moreno Peña."
[params.footer.radity_logo]
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
x = "img/general/design-and-code-radity.png"

[deployment]
  [[deployment.targets]]
    name = "S3 www.mingshome.xyz"
    URL = "s3://www.mingshome.xyz?region=ap-southeast-1"

  [[deployment.matchers]]
    pattern = "^.+\\.(png|jpg|webp)$"
    cacheControl = "max-age=86400"
    gzip = false