name: mingshome.xyz CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["main/**", "themes/**"]

defaults:
  run:
    working-directory: ./main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions: # for aws creds
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"  # Fetch Hugo themes (true OR recursive)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.136.5" # last version that has the deploy feature, see https://github.com/gohugoio/hugo/pull/12995
          extended: true
          
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Install PostCSS
        run: npm install postcss postcss-cli autoprefixer cssnano --save-dev

      - name: Build
        run: hugo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::913524912390:role/github-manage-s3-mingshome
          aws-region: ap-southeast-1

      - name: Deploy to S3
        run: hugo deploy
